/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    services: Service;
    doctors: Doctor;
    technology: Technology;
    testimonials: Testimonial;
    'hero-slides': HeroSlide;
    branches: Branch;
    'site-stats': SiteStat;
    'feature-cards': FeatureCard;
    'brand-logos': BrandLogo;
    'pricing-categories': PricingCategory;
    'pricing-items': PricingItem;
    'pricing-comparison-sets': PricingComparisonSet;
    'pricing-comparison-rows': PricingComparisonRow;
    'clinical-cases': ClinicalCase;
    'partner-categories': PartnerCategory;
    partners: Partner;
    'faq-items': FaqItem;
    'timeline-events': TimelineEvent;
    'international-treatments': InternationalTreatment;
    'international-steps': InternationalStep;
    'international-why-items': InternationalWhyItem;
    modules: Module;
    invoices: Invoice;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    technology: TechnologySelect<false> | TechnologySelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    'site-stats': SiteStatsSelect<false> | SiteStatsSelect<true>;
    'feature-cards': FeatureCardsSelect<false> | FeatureCardsSelect<true>;
    'brand-logos': BrandLogosSelect<false> | BrandLogosSelect<true>;
    'pricing-categories': PricingCategoriesSelect<false> | PricingCategoriesSelect<true>;
    'pricing-items': PricingItemsSelect<false> | PricingItemsSelect<true>;
    'pricing-comparison-sets': PricingComparisonSetsSelect<false> | PricingComparisonSetsSelect<true>;
    'pricing-comparison-rows': PricingComparisonRowsSelect<false> | PricingComparisonRowsSelect<true>;
    'clinical-cases': ClinicalCasesSelect<false> | ClinicalCasesSelect<true>;
    'partner-categories': PartnerCategoriesSelect<false> | PartnerCategoriesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'timeline-events': TimelineEventsSelect<false> | TimelineEventsSelect<true>;
    'international-treatments': InternationalTreatmentsSelect<false> | InternationalTreatmentsSelect<true>;
    'international-steps': InternationalStepsSelect<false> | InternationalStepsSelect<true>;
    'international-why-items': InternationalWhyItemsSelect<false> | InternationalWhyItemsSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'kh' | 'cn') | ('en' | 'kh' | 'cn')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'kh' | 'cn';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('super-admin' | 'tenant-admin' | 'editor')[];
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * URL-safe identifier, e.g. "roomchang"
   */
  slug: string;
  /**
   * Tenant logo — shown on their branded landing page and admin login (upload to the Media library first, under this tenant).
   */
  logo?: (number | null) | Media;
  /**
   * Hostnames that resolve to this tenant (host-based routing).
   */
  domains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Modules this tenant pays for. Price override falls back to the module’s default. Invoices auto-fill from active rows.
   */
  subscriptions?:
    | {
        module: number | Module;
        /**
         * USD/month for THIS tenant. Empty = module default price.
         */
        monthlyPrice?: number | null;
        /**
         * Uncheck to switch the module off for this tenant (e.g. AI Chatbot).
         */
        active?: boolean | null;
        startedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Sellable platform modules. Subscribe tenants to these on the Tenant document.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  name: string;
  /**
   * Stable slug used by sites to check the feature, e.g. "ai-chatbot".
   */
  key: string;
  description?: string | null;
  /**
   * USD per month. Can be overridden per tenant subscription.
   */
  defaultMonthlyPrice: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase services.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Small uppercase label above the hero title.
   */
  eyebrow?: string | null;
  /**
   * Longer hero paragraph (falls back to description).
   */
  heroDescription?: string | null;
  category?: string | null;
  /**
   * Icon name used on service cards.
   */
  icon?: string | null;
  isFeatured?: boolean | null;
  /**
   * The small pink tags on this service’s card on the "Services" overview page (/services) — a quick "what’s included" summary. NOT shown on this detail page, so the Live Preview won’t change when you edit these.
   */
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * R2 image URL (carried from the live site).
   */
  imageUrl?: string | null;
  /**
   * Detail-page sections JSON ({ sections: [...] }) — same shape the live site renders.
   */
  content?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase doctors.id (e.g. "dr-tak") — sync upsert key.
   */
  sourceId?: string | null;
  name: string;
  /**
   * e.g. "DDS, MSc."
   */
  credentials?: string | null;
  /**
   * e.g. "Orthodontist"
   */
  role?: string | null;
  /**
   * Team grouping, e.g. ORTHODONTICS (matches the live site enum).
   */
  department?: string | null;
  specialty?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  bio?: string | null;
  /**
   * Short credential highlight, e.g. "MSc. in Orthodontics — Germany, 2019"
   */
  note?: string | null;
  /**
   * Avatar fallback when no photo.
   */
  initials?: string | null;
  /**
   * R2 photo URL (carried from the live site).
   */
  photoUrl?: string | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technology".
 */
export interface Technology {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase technology.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  name: string;
  slug: string;
  category?: string | null;
  description?: string | null;
  highlights?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * R2 image URL (carried from the live site).
   */
  imageUrl?: string | null;
  /**
   * Detail-page content JSON — carried from the live site losslessly.
   */
  content?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase testimonials.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  authorName: string;
  authorTitle?: string | null;
  /**
   * Author photo URL (carried from the live site).
   */
  authorPhotoUrl?: string | null;
  quote?: string | null;
  rating?: number | null;
  isFeatured?: boolean | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase hero_slides.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  eyebrow?: string | null;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  /**
   * R2 image URL (carried from the live site).
   */
  imageUrl?: string | null;
  imageAlt?: string | null;
  imagePosition?: string | null;
  imageSize?: string | null;
  preserveFullImage?: boolean | null;
  ctaText?: string | null;
  ctaUrl?: string | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase branches.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  name: string;
  /**
   * Optional — the live branches table has no slugs; the sync derives one from the name.
   */
  slug?: string | null;
  shortName?: string | null;
  badge?: string | null;
  description?: string | null;
  address?: string | null;
  phone?: string | null;
  mobile?: string | null;
  email?: string | null;
  hours?: string | null;
  /**
   * R2 image URL (carried from the live site).
   */
  imageUrl?: string | null;
  mapQuery?: string | null;
  mapUrl?: string | null;
  mapPlaceUrl?: string | null;
  /**
   * Branch photos JSON — carried from the live site losslessly.
   */
  photos?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-stats".
 */
export interface SiteStat {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase site_stats.key — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  key: string;
  displayValue?: string | null;
  numericValue?: number | null;
  suffix?: string | null;
  label?: string | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-cards".
 */
export interface FeatureCard {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase homepage_feature_cards.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  slug: string;
  title: string;
  description?: string | null;
  /**
   * R2 image URL (carried from the live site).
   */
  imageUrl?: string | null;
  imageAlt?: string | null;
  href?: string | null;
  cta?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-logos".
 */
export interface BrandLogo {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase brand_logos.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  slug: string;
  name: string;
  /**
   * R2 logo URL (carried from the live site).
   */
  logoUrl?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-categories".
 */
export interface PricingCategory {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase pricing_categories.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  title: string;
  icon?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-items".
 */
export interface PricingItem {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase pricing_items.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  name: string;
  price?: string | null;
  ada?: string | null;
  aus?: string | null;
  note?: string | null;
  category?: (number | null) | PricingCategory;
  sourceCategoryId?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-comparison-sets".
 */
export interface PricingComparisonSet {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase pricing_comparison_sets.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  slug: string;
  exchangeRate?: number | null;
  sourceNote?: string | null;
  lastUpdated?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-comparison-rows".
 */
export interface PricingComparisonRow {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase pricing_comparison_rows.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  set?: (number | null) | PricingComparisonSet;
  sourceSetId?: string | null;
  ada?: string | null;
  treatment: string;
  roomchangPrice?: string | null;
  australiaPrice?: string | null;
  singaporePrice?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinical-cases".
 */
export interface ClinicalCase {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase clinical_cases.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  title: string;
  slug: string;
  category?: string | null;
  treatment?: string | null;
  duration?: string | null;
  description?: string | null;
  tag?: string | null;
  fullText?: string | null;
  /**
   * R2 image URL (carried from clinical_cases.imageUrl).
   */
  imageUrl?: string | null;
  /**
   * Clinical case images JSON — carried from the live site losslessly.
   */
  images?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-categories".
 */
export interface PartnerCategory {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase partner_categories.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  name: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase partners.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  name: string;
  /**
   * R2 logo URL (carried from partners.logo_src).
   */
  logoUrl?: string | null;
  website?: string | null;
  category?: (number | null) | PartnerCategory;
  sourceCategoryId?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase faq_items.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  question: string;
  answer?: string | null;
  category?: string | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events".
 */
export interface TimelineEvent {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase timeline_events.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  year: string;
  caption?: string | null;
  heading: string;
  body?: string | null;
  /**
   * R2 image URL (carried from timeline_events.imageSrc).
   */
  imageUrl?: string | null;
  imageAlt?: string | null;
  imagePosition?: string | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "international-treatments".
 */
export interface InternationalTreatment {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase international_popular_treatments.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  name: string;
  saving?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "international-steps".
 */
export interface InternationalStep {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase international_steps.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  stepLabel?: string | null;
  title: string;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "international-why-items".
 */
export interface InternationalWhyItem {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Supabase international_why_items.id — used by the sync for idempotent upserts.
   */
  sourceId?: string | null;
  title: string;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create an invoice with an empty line-item list to auto-fill it from the tenant’s active subscriptions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  tenant: number | Tenant;
  periodStart: string;
  periodEnd: string;
  /**
   * Once an invoice leaves Draft, its line items are locked.
   */
  status: 'draft' | 'sent' | 'paid';
  /**
   * Leave empty on create to auto-fill from the tenant’s active subscriptions.
   */
  lineItems?:
    | {
        /**
         * Snapshot of the module key at invoicing time (audit trail).
         */
        moduleKey?: string | null;
        description: string;
        amount: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Computed from line items.
   */
  total?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'technology';
        value: number | Technology;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'site-stats';
        value: number | SiteStat;
      } | null)
    | ({
        relationTo: 'feature-cards';
        value: number | FeatureCard;
      } | null)
    | ({
        relationTo: 'brand-logos';
        value: number | BrandLogo;
      } | null)
    | ({
        relationTo: 'pricing-categories';
        value: number | PricingCategory;
      } | null)
    | ({
        relationTo: 'pricing-items';
        value: number | PricingItem;
      } | null)
    | ({
        relationTo: 'pricing-comparison-sets';
        value: number | PricingComparisonSet;
      } | null)
    | ({
        relationTo: 'pricing-comparison-rows';
        value: number | PricingComparisonRow;
      } | null)
    | ({
        relationTo: 'clinical-cases';
        value: number | ClinicalCase;
      } | null)
    | ({
        relationTo: 'partner-categories';
        value: number | PartnerCategory;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'timeline-events';
        value: number | TimelineEvent;
      } | null)
    | ({
        relationTo: 'international-treatments';
        value: number | InternationalTreatment;
      } | null)
    | ({
        relationTo: 'international-steps';
        value: number | InternationalStep;
      } | null)
    | ({
        relationTo: 'international-why-items';
        value: number | InternationalWhyItem;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  subscriptions?:
    | T
    | {
        module?: T;
        monthlyPrice?: T;
        active?: T;
        startedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  name?: T;
  slug?: T;
  description?: T;
  eyebrow?: T;
  heroDescription?: T;
  category?: T;
  icon?: T;
  isFeatured?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  imageUrl?: T;
  content?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  name?: T;
  credentials?: T;
  role?: T;
  department?: T;
  specialty?:
    | T
    | {
        value?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        value?: T;
        id?: T;
      };
  bio?: T;
  note?: T;
  initials?: T;
  photoUrl?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technology_select".
 */
export interface TechnologySelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  name?: T;
  slug?: T;
  category?: T;
  description?: T;
  highlights?:
    | T
    | {
        value?: T;
        id?: T;
      };
  imageUrl?: T;
  content?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  authorName?: T;
  authorTitle?: T;
  authorPhotoUrl?: T;
  quote?: T;
  rating?: T;
  isFeatured?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  imageUrl?: T;
  imageAlt?: T;
  imagePosition?: T;
  imageSize?: T;
  preserveFullImage?: T;
  ctaText?: T;
  ctaUrl?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  name?: T;
  slug?: T;
  shortName?: T;
  badge?: T;
  description?: T;
  address?: T;
  phone?: T;
  mobile?: T;
  email?: T;
  hours?: T;
  imageUrl?: T;
  mapQuery?: T;
  mapUrl?: T;
  mapPlaceUrl?: T;
  photos?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-stats_select".
 */
export interface SiteStatsSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  key?: T;
  displayValue?: T;
  numericValue?: T;
  suffix?: T;
  label?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-cards_select".
 */
export interface FeatureCardsSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  slug?: T;
  title?: T;
  description?: T;
  imageUrl?: T;
  imageAlt?: T;
  href?: T;
  cta?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-logos_select".
 */
export interface BrandLogosSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  slug?: T;
  name?: T;
  logoUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-categories_select".
 */
export interface PricingCategoriesSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  title?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-items_select".
 */
export interface PricingItemsSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  name?: T;
  price?: T;
  ada?: T;
  aus?: T;
  note?: T;
  category?: T;
  sourceCategoryId?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-comparison-sets_select".
 */
export interface PricingComparisonSetsSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  slug?: T;
  exchangeRate?: T;
  sourceNote?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-comparison-rows_select".
 */
export interface PricingComparisonRowsSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  set?: T;
  sourceSetId?: T;
  ada?: T;
  treatment?: T;
  roomchangPrice?: T;
  australiaPrice?: T;
  singaporePrice?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinical-cases_select".
 */
export interface ClinicalCasesSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  title?: T;
  slug?: T;
  category?: T;
  treatment?: T;
  duration?: T;
  description?: T;
  tag?: T;
  fullText?: T;
  imageUrl?: T;
  images?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-categories_select".
 */
export interface PartnerCategoriesSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  name?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  name?: T;
  logoUrl?: T;
  website?: T;
  category?: T;
  sourceCategoryId?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events_select".
 */
export interface TimelineEventsSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  year?: T;
  caption?: T;
  heading?: T;
  body?: T;
  imageUrl?: T;
  imageAlt?: T;
  imagePosition?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "international-treatments_select".
 */
export interface InternationalTreatmentsSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  name?: T;
  saving?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "international-steps_select".
 */
export interface InternationalStepsSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  stepLabel?: T;
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "international-why-items_select".
 */
export interface InternationalWhyItemsSelect<T extends boolean = true> {
  tenant?: T;
  sourceId?: T;
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  description?: T;
  defaultMonthlyPrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  tenant?: T;
  periodStart?: T;
  periodEnd?: T;
  status?: T;
  lineItems?:
    | T
    | {
        moduleKey?: T;
        description?: T;
        amount?: T;
        id?: T;
      };
  total?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}